// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/company/proto/company.proto

package companypb

import (
	context "context"
	fmt "fmt"
	_ "github.com/fzerorubigd/protobuf/extra"
	types "github.com/fzerorubigd/protobuf/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CompanyStatus int32

const (
	CompanyStatus_COMPANY_STATUS_INVALID CompanyStatus = 0
	CompanyStatus_COMPANY_STATUS_PENDING CompanyStatus = 1
	CompanyStatus_COMPANY_STATUS_ACTIVE  CompanyStatus = 2
	CompanyStatus_COMPANY_STATUS_BANNED  CompanyStatus = 3
)

var CompanyStatus_name = map[int32]string{
	0: "COMPANY_STATUS_INVALID",
	1: "COMPANY_STATUS_PENDING",
	2: "COMPANY_STATUS_ACTIVE",
	3: "COMPANY_STATUS_BANNED",
}

var CompanyStatus_value = map[string]int32{
	"COMPANY_STATUS_INVALID": 0,
	"COMPANY_STATUS_PENDING": 1,
	"COMPANY_STATUS_ACTIVE":  2,
	"COMPANY_STATUS_BANNED":  3,
}

func (x CompanyStatus) String() string {
	return proto.EnumName(CompanyStatus_name, int32(x))
}

func (CompanyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{0}
}

type Company struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" `
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" db:"name" `
	Status               CompanyStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=company.CompanyStatus" json:"status,omitempty" db:"status" `
	CreatedAt            *types.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at" `
	UpdatedAt            *types.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at" `
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{0}
}
func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetStatus() CompanyStatus {
	if m != nil {
		return m.Status
	}
	return CompanyStatus_COMPANY_STATUS_INVALID
}

func (m *Company) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Company) GetUpdatedAt() *types.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetCompanyRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyRequest) Reset()         { *m = GetCompanyRequest{} }
func (m *GetCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompanyRequest) ProtoMessage()    {}
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{1}
}
func (m *GetCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyRequest.Unmarshal(m, b)
}
func (m *GetCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyRequest.Marshal(b, m, deterministic)
}
func (m *GetCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyRequest.Merge(m, src)
}
func (m *GetCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompanyRequest.Size(m)
}
func (m *GetCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyRequest proto.InternalMessageInfo

func (m *GetCompanyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCompanyResponse struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               CompanyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=company.CompanyStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCompanyResponse) Reset()         { *m = GetCompanyResponse{} }
func (m *GetCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse) ProtoMessage()    {}
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{2}
}
func (m *GetCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse.Unmarshal(m, b)
}
func (m *GetCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse.Merge(m, src)
}
func (m *GetCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse.Size(m)
}
func (m *GetCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse proto.InternalMessageInfo

func (m *GetCompanyResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetCompanyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCompanyResponse) GetStatus() CompanyStatus {
	if m != nil {
		return m.Status
	}
	return CompanyStatus_COMPANY_STATUS_INVALID
}

type CreateCompanyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyRequest) Reset()         { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()    {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{3}
}
func (m *CreateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyRequest.Unmarshal(m, b)
}
func (m *CreateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *CreateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyRequest.Merge(m, src)
}
func (m *CreateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyRequest.Size(m)
}
func (m *CreateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyRequest proto.InternalMessageInfo

func (m *CreateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateCompanyResponse struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               CompanyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=company.CompanyStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateCompanyResponse) Reset()         { *m = CreateCompanyResponse{} }
func (m *CreateCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyResponse) ProtoMessage()    {}
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{4}
}
func (m *CreateCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyResponse.Unmarshal(m, b)
}
func (m *CreateCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyResponse.Marshal(b, m, deterministic)
}
func (m *CreateCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyResponse.Merge(m, src)
}
func (m *CreateCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyResponse.Size(m)
}
func (m *CreateCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyResponse proto.InternalMessageInfo

func (m *CreateCompanyResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateCompanyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompanyResponse) GetStatus() CompanyStatus {
	if m != nil {
		return m.Status
	}
	return CompanyStatus_COMPANY_STATUS_INVALID
}

func init() {
	proto.RegisterEnum("company.CompanyStatus", CompanyStatus_name, CompanyStatus_value)
	proto.RegisterType((*Company)(nil), "company.Company")
	proto.RegisterType((*GetCompanyRequest)(nil), "company.GetCompanyRequest")
	proto.RegisterType((*GetCompanyResponse)(nil), "company.GetCompanyResponse")
	proto.RegisterType((*CreateCompanyRequest)(nil), "company.CreateCompanyRequest")
	proto.RegisterType((*CreateCompanyResponse)(nil), "company.CreateCompanyResponse")
}

func init() {
	proto.RegisterFile("modules/company/proto/company.proto", fileDescriptor_24f2033e12fc8969)
}

var fileDescriptor_24f2033e12fc8969 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x6f, 0xd3, 0x3e,
	0x1c, 0x5d, 0xd2, 0xfd, 0xb7, 0xff, 0xbc, 0xad, 0xca, 0xac, 0x6e, 0x6a, 0xc3, 0xa0, 0x91, 0x77,
	0xa9, 0x26, 0xd6, 0xb0, 0x21, 0x84, 0xb4, 0x13, 0x49, 0x57, 0x4d, 0x95, 0xa0, 0x54, 0x5d, 0x99,
	0x04, 0x97, 0xc9, 0x69, 0xbc, 0x2c, 0x62, 0x89, 0x43, 0xec, 0x00, 0x05, 0x8d, 0x03, 0x12, 0x97,
	0x1d, 0xe1, 0xc0, 0xb7, 0x00, 0x89, 0x4f, 0xc1, 0x9d, 0x1b, 0x87, 0x9e, 0xf8, 0x00, 0x53, 0x3f,
	0x01, 0x4a, 0xe2, 0x2c, 0x5b, 0x57, 0x34, 0x2e, 0x5c, 0xdc, 0xfe, 0xfa, 0xde, 0xfb, 0xf9, 0xfd,
	0x9e, 0x5d, 0x83, 0x35, 0x8f, 0xda, 0xd1, 0x31, 0x61, 0x7a, 0x9f, 0x7a, 0x01, 0xf6, 0x07, 0x7a,
	0x10, 0x52, 0x4e, 0xb3, 0xaa, 0x9e, 0x54, 0x70, 0x56, 0x94, 0xea, 0xa6, 0xe3, 0xf2, 0xa3, 0xc8,
	0xaa, 0xf7, 0xa9, 0xa7, 0x1f, 0xbe, 0x21, 0x21, 0x0d, 0x23, 0xcb, 0x75, 0xec, 0x54, 0x64, 0x45,
	0x87, 0x3a, 0x79, 0xcd, 0x43, 0x9c, 0xae, 0xa9, 0x56, 0xbd, 0x73, 0x9d, 0x84, 0x0f, 0x02, 0xc2,
	0x92, 0x55, 0x28, 0x36, 0x2e, 0x28, 0x1c, 0xea, 0xd0, 0x9c, 0x1a, 0x57, 0xa9, 0xbf, 0xf8, 0x9b,
	0xa0, 0xaf, 0x3a, 0x94, 0x3a, 0xc7, 0x44, 0xc7, 0x81, 0xab, 0x63, 0xdf, 0xa7, 0x1c, 0x73, 0x97,
	0xfa, 0x4c, 0xa0, 0xb7, 0x93, 0x8f, 0xfe, 0x86, 0x43, 0xfc, 0x0d, 0xf6, 0x0a, 0x3b, 0x0e, 0x09,
	0x75, 0x1a, 0x24, 0x8c, 0xab, 0x6c, 0xf4, 0x45, 0x06, 0xb3, 0x8d, 0x74, 0x56, 0xb8, 0x0a, 0x64,
	0xd7, 0x2e, 0x4b, 0x9a, 0x54, 0x2b, 0x98, 0x0b, 0xa3, 0x61, 0xf5, 0x7f, 0xdb, 0xda, 0x46, 0xae,
	0x8d, 0xb4, 0xae, 0xec, 0xda, 0x10, 0x81, 0x69, 0x1f, 0x7b, 0xa4, 0x2c, 0x6b, 0x52, 0x6d, 0xce,
	0x2c, 0x8e, 0x86, 0x55, 0x10, 0xe3, 0xf1, 0x6f, 0x48, 0xeb, 0x26, 0x18, 0x7c, 0x00, 0x66, 0x18,
	0xc7, 0x3c, 0x62, 0xe5, 0x82, 0x26, 0xd5, 0x8a, 0x5b, 0x2b, 0xf5, 0x2c, 0x56, 0xb1, 0xc7, 0x5e,
	0x82, 0x9a, 0xca, 0x68, 0x58, 0x5d, 0x88, 0xd5, 0x29, 0x1b, 0x69, 0x5d, 0xa1, 0x83, 0x4d, 0x00,
	0xfa, 0x21, 0xc1, 0x9c, 0xd8, 0x07, 0x98, 0x97, 0xa7, 0x35, 0xa9, 0x36, 0xbf, 0xa5, 0xd4, 0x93,
	0xc4, 0xea, 0x3d, 0xd7, 0x23, 0x8c, 0x63, 0x2f, 0x30, 0x4b, 0xa3, 0x61, 0x55, 0x89, 0xf5, 0x39,
	0x17, 0x69, 0xdd, 0x39, 0x51, 0x19, 0x3c, 0x6e, 0x13, 0x05, 0x76, 0xd6, 0xe6, 0xbf, 0xeb, 0xda,
	0xe4, 0xdc, 0xb8, 0x8d, 0xa8, 0x0c, 0xbe, 0xbd, 0xf4, 0xfd, 0xac, 0x22, 0xfd, 0x3c, 0xab, 0xcc,
	0xa5, 0x63, 0xb8, 0x84, 0xa1, 0x35, 0xb0, 0xb4, 0x4b, 0xb8, 0x18, 0xa7, 0x4b, 0x5e, 0x44, 0x84,
	0x71, 0x58, 0xcc, 0x93, 0x8b, 0xb3, 0x42, 0x47, 0x00, 0x5e, 0x24, 0xb1, 0x80, 0xfa, 0x8c, 0x8c,
	0xb3, 0x20, 0xbc, 0x98, 0xa8, 0x48, 0xb0, 0xfe, 0x77, 0x09, 0x66, 0x79, 0xa1, 0x75, 0x50, 0x6a,
	0x24, 0x53, 0x8f, 0x39, 0xca, 0x7a, 0x4b, 0x79, 0x6f, 0xf4, 0x1c, 0x2c, 0x8f, 0x71, 0xff, 0x9d,
	0xb1, 0xf5, 0x13, 0xb0, 0x78, 0x09, 0x80, 0x2a, 0x58, 0x69, 0x3c, 0x7e, 0xd4, 0x31, 0xda, 0x4f,
	0x0f, 0xf6, 0x7a, 0x46, 0xef, 0xc9, 0xde, 0x41, 0xab, 0xbd, 0x6f, 0x3c, 0x6c, 0xed, 0x28, 0x53,
	0x13, 0xb0, 0x4e, 0xb3, 0xbd, 0xd3, 0x6a, 0xef, 0x2a, 0x12, 0xac, 0x80, 0xe5, 0x31, 0xcc, 0x68,
	0xf4, 0x5a, 0xfb, 0x4d, 0x45, 0x9e, 0x00, 0x99, 0x46, 0xbb, 0xdd, 0xdc, 0x51, 0x0a, 0x5b, 0x9f,
	0xe5, 0x7c, 0xff, 0x01, 0xe3, 0xc4, 0x83, 0xef, 0x00, 0xc8, 0xcf, 0x04, 0xaa, 0xe7, 0xf6, 0xaf,
	0x9c, 0xa6, 0x7a, 0x63, 0x22, 0x96, 0x66, 0x85, 0xee, 0x7f, 0x34, 0x56, 0xac, 0x12, 0x80, 0xa0,
	0x68, 0x44, 0xfc, 0x88, 0xf8, 0xdc, 0xed, 0x27, 0x7f, 0x28, 0x38, 0x75, 0xfa, 0x55, 0x9d, 0x7a,
	0xff, 0xe3, 0xd7, 0x27, 0xb9, 0x04, 0xa1, 0xfe, 0x72, 0x53, 0x3f, 0xbf, 0x33, 0xfa, 0x5b, 0xd7,
	0x3e, 0x81, 0x1f, 0x24, 0xb0, 0x78, 0x29, 0x7e, 0x78, 0x33, 0x8f, 0x70, 0xc2, 0x11, 0xaa, 0xb7,
	0xfe, 0x04, 0x0b, 0x27, 0xf7, 0xae, 0x77, 0x02, 0xd1, 0xe2, 0x25, 0x27, 0xdb, 0xd2, 0xba, 0xa9,
	0x9f, 0x7e, 0xab, 0x14, 0x30, 0xc6, 0x60, 0xbe, 0x4f, 0xbd, 0x6c, 0x0b, 0x73, 0x41, 0x74, 0xef,
	0xc4, 0xaf, 0x42, 0x47, 0x7a, 0x26, 0x6e, 0xfc, 0x20, 0xb0, 0xac, 0x99, 0xe4, 0xa5, 0xb8, 0xfb,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xb0, 0x9e, 0x48, 0x39, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CompanySystemClient is the client API for CompanySystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompanySystemClient interface {
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*GetCompanyResponse, error)
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyResponse, error)
}

type companySystemClient struct {
	cc *grpc.ClientConn
}

func NewCompanySystemClient(cc *grpc.ClientConn) CompanySystemClient {
	return &companySystemClient{cc}
}

func (c *companySystemClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*GetCompanyResponse, error) {
	out := new(GetCompanyResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/GetCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companySystemClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyResponse, error) {
	out := new(CreateCompanyResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/CreateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanySystemServer is the server API for CompanySystem service.
type CompanySystemServer interface {
	GetCompany(context.Context, *GetCompanyRequest) (*GetCompanyResponse, error)
	CreateCompany(context.Context, *CreateCompanyRequest) (*CreateCompanyResponse, error)
}

// UnimplementedCompanySystemServer can be embedded to have forward compatible implementations.
type UnimplementedCompanySystemServer struct {
}

func (*UnimplementedCompanySystemServer) GetCompany(ctx context.Context, req *GetCompanyRequest) (*GetCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}
func (*UnimplementedCompanySystemServer) CreateCompany(ctx context.Context, req *CreateCompanyRequest) (*CreateCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompany not implemented")
}

func RegisterCompanySystemServer(s *grpc.Server, srv CompanySystemServer) {
	s.RegisterService(&_CompanySystem_serviceDesc, srv)
}

func _CompanySystem_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/GetCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanySystem_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompanySystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "company.CompanySystem",
	HandlerType: (*CompanySystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompany",
			Handler:    _CompanySystem_GetCompany_Handler,
		},
		{
			MethodName: "CreateCompany",
			Handler:    _CompanySystem_CreateCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/company/proto/company.proto",
}
