// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/company/proto/company.proto

package companypb

import (
	context "context"
	fmt "fmt"
	_ "github.com/fzerorubigd/protobuf/extra"
	types "github.com/fzerorubigd/protobuf/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CompanyStatus int32

const (
	CompanyStatus_COMPANY_STATUS_INVALID CompanyStatus = 0
	CompanyStatus_COMPANY_STATUS_PENDING CompanyStatus = 1
	CompanyStatus_COMPANY_STATUS_ACTIVE  CompanyStatus = 2
	CompanyStatus_COMPANY_STATUS_BANNED  CompanyStatus = 3
)

var CompanyStatus_name = map[int32]string{
	0: "COMPANY_STATUS_INVALID",
	1: "COMPANY_STATUS_PENDING",
	2: "COMPANY_STATUS_ACTIVE",
	3: "COMPANY_STATUS_BANNED",
}

var CompanyStatus_value = map[string]int32{
	"COMPANY_STATUS_INVALID": 0,
	"COMPANY_STATUS_PENDING": 1,
	"COMPANY_STATUS_ACTIVE":  2,
	"COMPANY_STATUS_BANNED":  3,
}

func (x CompanyStatus) String() string {
	return proto.EnumName(CompanyStatus_name, int32(x))
}

func (CompanyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{0}
}

type Company struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" `
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" db:"name" `
	Status               CompanyStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=company.CompanyStatus" json:"status,omitempty" db:"status" `
	CreatedAt            *types.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at" `
	UpdatedAt            *types.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at" `
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{0}
}
func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetStatus() CompanyStatus {
	if m != nil {
		return m.Status
	}
	return CompanyStatus_COMPANY_STATUS_INVALID
}

func (m *Company) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Company) GetUpdatedAt() *types.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetCompanyRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyRequest) Reset()         { *m = GetCompanyRequest{} }
func (m *GetCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompanyRequest) ProtoMessage()    {}
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{1}
}
func (m *GetCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyRequest.Unmarshal(m, b)
}
func (m *GetCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyRequest.Marshal(b, m, deterministic)
}
func (m *GetCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyRequest.Merge(m, src)
}
func (m *GetCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompanyRequest.Size(m)
}
func (m *GetCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyRequest proto.InternalMessageInfo

func (m *GetCompanyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CompanyResponse struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               CompanyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=company.CompanyStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CompanyResponse) Reset()         { *m = CompanyResponse{} }
func (m *CompanyResponse) String() string { return proto.CompactTextString(m) }
func (*CompanyResponse) ProtoMessage()    {}
func (*CompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{2}
}
func (m *CompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyResponse.Unmarshal(m, b)
}
func (m *CompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyResponse.Marshal(b, m, deterministic)
}
func (m *CompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyResponse.Merge(m, src)
}
func (m *CompanyResponse) XXX_Size() int {
	return xxx_messageInfo_CompanyResponse.Size(m)
}
func (m *CompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyResponse proto.InternalMessageInfo

func (m *CompanyResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CompanyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompanyResponse) GetStatus() CompanyStatus {
	if m != nil {
		return m.Status
	}
	return CompanyStatus_COMPANY_STATUS_INVALID
}

type CreateCompanyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyRequest) Reset()         { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()    {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{3}
}
func (m *CreateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyRequest.Unmarshal(m, b)
}
func (m *CreateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *CreateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyRequest.Merge(m, src)
}
func (m *CreateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyRequest.Size(m)
}
func (m *CreateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyRequest proto.InternalMessageInfo

func (m *CreateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCompaniesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompaniesRequest) Reset()         { *m = GetCompaniesRequest{} }
func (m *GetCompaniesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompaniesRequest) ProtoMessage()    {}
func (*GetCompaniesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{4}
}
func (m *GetCompaniesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompaniesRequest.Unmarshal(m, b)
}
func (m *GetCompaniesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompaniesRequest.Marshal(b, m, deterministic)
}
func (m *GetCompaniesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompaniesRequest.Merge(m, src)
}
func (m *GetCompaniesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompaniesRequest.Size(m)
}
func (m *GetCompaniesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompaniesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompaniesRequest proto.InternalMessageInfo

type CompaniesResponse struct {
	Companies            []*CompanyResponse `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CompaniesResponse) Reset()         { *m = CompaniesResponse{} }
func (m *CompaniesResponse) String() string { return proto.CompactTextString(m) }
func (*CompaniesResponse) ProtoMessage()    {}
func (*CompaniesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{5}
}
func (m *CompaniesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompaniesResponse.Unmarshal(m, b)
}
func (m *CompaniesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompaniesResponse.Marshal(b, m, deterministic)
}
func (m *CompaniesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompaniesResponse.Merge(m, src)
}
func (m *CompaniesResponse) XXX_Size() int {
	return xxx_messageInfo_CompaniesResponse.Size(m)
}
func (m *CompaniesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompaniesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompaniesResponse proto.InternalMessageInfo

func (m *CompaniesResponse) GetCompanies() []*CompanyResponse {
	if m != nil {
		return m.Companies
	}
	return nil
}

type DeleteCompanyRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCompanyRequest) Reset()         { *m = DeleteCompanyRequest{} }
func (m *DeleteCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCompanyRequest) ProtoMessage()    {}
func (*DeleteCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{6}
}
func (m *DeleteCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCompanyRequest.Unmarshal(m, b)
}
func (m *DeleteCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCompanyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCompanyRequest.Merge(m, src)
}
func (m *DeleteCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCompanyRequest.Size(m)
}
func (m *DeleteCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCompanyRequest proto.InternalMessageInfo

func (m *DeleteCompanyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCompanyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCompanyResponse) Reset()         { *m = DeleteCompanyResponse{} }
func (m *DeleteCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCompanyResponse) ProtoMessage()    {}
func (*DeleteCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{7}
}
func (m *DeleteCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCompanyResponse.Unmarshal(m, b)
}
func (m *DeleteCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCompanyResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCompanyResponse.Merge(m, src)
}
func (m *DeleteCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCompanyResponse.Size(m)
}
func (m *DeleteCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCompanyResponse proto.InternalMessageInfo

type UpdateCompanyRequest struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               CompanyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=company.CompanyStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateCompanyRequest) Reset()         { *m = UpdateCompanyRequest{} }
func (m *UpdateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyRequest) ProtoMessage()    {}
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f2033e12fc8969, []int{8}
}
func (m *UpdateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyRequest.Merge(m, src)
}
func (m *UpdateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyRequest.Size(m)
}
func (m *UpdateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyRequest proto.InternalMessageInfo

func (m *UpdateCompanyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCompanyRequest) GetStatus() CompanyStatus {
	if m != nil {
		return m.Status
	}
	return CompanyStatus_COMPANY_STATUS_INVALID
}

func init() {
	proto.RegisterEnum("company.CompanyStatus", CompanyStatus_name, CompanyStatus_value)
	proto.RegisterType((*Company)(nil), "company.Company")
	proto.RegisterType((*GetCompanyRequest)(nil), "company.GetCompanyRequest")
	proto.RegisterType((*CompanyResponse)(nil), "company.CompanyResponse")
	proto.RegisterType((*CreateCompanyRequest)(nil), "company.CreateCompanyRequest")
	proto.RegisterType((*GetCompaniesRequest)(nil), "company.GetCompaniesRequest")
	proto.RegisterType((*CompaniesResponse)(nil), "company.CompaniesResponse")
	proto.RegisterType((*DeleteCompanyRequest)(nil), "company.DeleteCompanyRequest")
	proto.RegisterType((*DeleteCompanyResponse)(nil), "company.DeleteCompanyResponse")
	proto.RegisterType((*UpdateCompanyRequest)(nil), "company.UpdateCompanyRequest")
}

func init() {
	proto.RegisterFile("modules/company/proto/company.proto", fileDescriptor_24f2033e12fc8969)
}

var fileDescriptor_24f2033e12fc8969 = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcb, 0x6e, 0xd3, 0x5a,
	0x14, 0xad, 0x93, 0x3e, 0x6e, 0x77, 0x93, 0x34, 0x3d, 0x37, 0x6d, 0x13, 0xab, 0xf7, 0xc6, 0x3a,
	0x95, 0xae, 0xa2, 0xe8, 0x36, 0xa6, 0x41, 0x80, 0x94, 0x11, 0xce, 0x43, 0x55, 0x04, 0x84, 0x28,
	0x4d, 0x2b, 0xc1, 0xa4, 0x72, 0xe2, 0x53, 0xd7, 0xa8, 0x7e, 0x10, 0x1f, 0x03, 0xa1, 0x54, 0x48,
	0x08, 0x09, 0xa9, 0x43, 0x98, 0xf2, 0x0d, 0x20, 0xf1, 0x15, 0xcc, 0x99, 0x31, 0xc8, 0x88, 0x0f,
	0xa8, 0xf2, 0x05, 0xc8, 0x8f, 0xc4, 0xce, 0xa3, 0x0d, 0x48, 0x4c, 0x9c, 0x6c, 0xef, 0xb5, 0xf7,
	0x5e, 0x7b, 0x9d, 0x75, 0x64, 0xd8, 0x56, 0x75, 0xc9, 0x3a, 0x25, 0x26, 0xdf, 0xd6, 0x55, 0x43,
	0xd4, 0xba, 0xbc, 0xd1, 0xd1, 0xa9, 0x3e, 0x88, 0x72, 0x4e, 0x84, 0x96, 0xbc, 0x90, 0xdd, 0x95,
	0x15, 0x7a, 0x62, 0xb5, 0x72, 0x6d, 0x5d, 0xe5, 0x8f, 0x5f, 0x92, 0x8e, 0xde, 0xb1, 0x5a, 0x8a,
	0x2c, 0xb9, 0x45, 0x2d, 0xeb, 0x98, 0x27, 0x2f, 0x68, 0x47, 0x74, 0x9f, 0x6e, 0x2d, 0x7b, 0x63,
	0x56, 0x09, 0xed, 0x1a, 0xc4, 0x74, 0x9e, 0x5e, 0xc5, 0x4e, 0xa0, 0x42, 0xd6, 0x65, 0xdd, 0x87,
	0xda, 0x91, 0xcb, 0xcf, 0xfe, 0xe7, 0xc1, 0xb7, 0x64, 0x5d, 0x97, 0x4f, 0x09, 0x2f, 0x1a, 0x0a,
	0x2f, 0x6a, 0x9a, 0x4e, 0x45, 0xaa, 0xe8, 0x9a, 0xe9, 0x65, 0xff, 0x77, 0x7e, 0xda, 0x3b, 0x32,
	0xd1, 0x76, 0xcc, 0xe7, 0xa2, 0x2c, 0x93, 0x0e, 0xaf, 0x1b, 0x0e, 0x62, 0x12, 0x8d, 0x3f, 0x85,
	0x60, 0xa9, 0xe4, 0xee, 0x8a, 0xb6, 0x20, 0xa4, 0x48, 0x49, 0x86, 0x63, 0x32, 0xe1, 0x62, 0xa4,
	0xdf, 0x4b, 0xff, 0x25, 0xb5, 0x0a, 0x58, 0x91, 0x30, 0xd7, 0x08, 0x29, 0x12, 0xc2, 0x30, 0xaf,
	0x89, 0x2a, 0x49, 0x86, 0x38, 0x26, 0xb3, 0x5c, 0x8c, 0xf5, 0x7b, 0x69, 0xb0, 0xf3, 0xf6, 0x3b,
	0xcc, 0x35, 0x9c, 0x1c, 0xba, 0x0b, 0x8b, 0x26, 0x15, 0xa9, 0x65, 0x26, 0xc3, 0x1c, 0x93, 0x89,
	0xe5, 0x37, 0x72, 0x03, 0x59, 0xbd, 0x19, 0xfb, 0x4e, 0xb6, 0x18, 0xef, 0xf7, 0xd2, 0x11, 0xbb,
	0xda, 0x45, 0x63, 0xae, 0xe1, 0xd5, 0xa1, 0x0a, 0x40, 0xbb, 0x43, 0x44, 0x4a, 0xa4, 0x23, 0x91,
	0x26, 0xe7, 0x39, 0x26, 0xb3, 0x92, 0x8f, 0xe7, 0x1c, 0xc5, 0x72, 0x4d, 0x45, 0x25, 0x26, 0x15,
	0x55, 0xa3, 0x98, 0xe8, 0xf7, 0xd2, 0x71, 0xbb, 0xde, 0xc7, 0x62, 0xae, 0xb1, 0xec, 0x45, 0x02,
	0xb5, 0xdb, 0x58, 0x86, 0x34, 0x68, 0xb3, 0x30, 0xab, 0x8d, 0x8f, 0xb5, 0xdb, 0x78, 0x91, 0x40,
	0x0b, 0x6b, 0x5f, 0x2f, 0x53, 0xcc, 0xf7, 0xcb, 0xd4, 0xb2, 0xbb, 0x86, 0x42, 0x4c, 0xbc, 0x0d,
	0x6b, 0x7b, 0x84, 0x7a, 0xeb, 0x34, 0xc8, 0x53, 0x8b, 0x98, 0x14, 0xc5, 0x7c, 0xe5, 0x6c, 0xad,
	0x30, 0x81, 0xd5, 0x21, 0xc2, 0x34, 0x74, 0xcd, 0x24, 0xe3, 0x10, 0x84, 0x82, 0x72, 0x7a, 0xf2,
	0xe5, 0x7e, 0x4d, 0xbe, 0x81, 0x58, 0x38, 0x0b, 0x89, 0x92, 0xb3, 0xf2, 0x18, 0x9d, 0x41, 0x6f,
	0xc6, 0xef, 0x8d, 0xd7, 0xe1, 0xef, 0x21, 0x6f, 0x85, 0x98, 0x1e, 0x14, 0xdf, 0x83, 0xb5, 0xc0,
	0x3b, 0x8f, 0xeb, 0x6d, 0xf0, 0x17, 0x4e, 0x32, 0x5c, 0x38, 0xb3, 0x92, 0x4f, 0x8e, 0x53, 0x19,
	0x80, 0x1b, 0x01, 0x6d, 0xfe, 0x83, 0x44, 0x99, 0x9c, 0x92, 0x09, 0x3e, 0xe3, 0xf2, 0x6c, 0xc2,
	0xfa, 0x18, 0xce, 0xed, 0x85, 0x9f, 0x40, 0xe2, 0xc0, 0x11, 0xff, 0xfa, 0x06, 0x7f, 0x42, 0xbc,
	0xec, 0x39, 0x44, 0x47, 0x12, 0x88, 0x85, 0x8d, 0xd2, 0xc3, 0x07, 0x75, 0xa1, 0xf6, 0xe8, 0x68,
	0xbf, 0x29, 0x34, 0x0f, 0xf6, 0x8f, 0xaa, 0xb5, 0x43, 0xe1, 0x7e, 0xb5, 0x1c, 0x9f, 0x9b, 0x92,
	0xab, 0x57, 0x6a, 0xe5, 0x6a, 0x6d, 0x2f, 0xce, 0xa0, 0x14, 0xac, 0x8f, 0xe5, 0x84, 0x52, 0xb3,
	0x7a, 0x58, 0x89, 0x87, 0xa6, 0xa4, 0x8a, 0x42, 0xad, 0x56, 0x29, 0xc7, 0xc3, 0xf9, 0x8f, 0x0b,
	0xfe, 0xfc, 0xae, 0x49, 0x89, 0x8a, 0xce, 0x00, 0x7c, 0x67, 0x21, 0x76, 0x48, 0x7f, 0xc2, 0x6e,
	0xec, 0x95, 0x87, 0x81, 0xef, 0xbc, 0x17, 0x36, 0x5a, 0x09, 0x40, 0x10, 0x13, 0x2c, 0x7a, 0x42,
	0x34, 0xaa, 0xb4, 0x9d, 0xeb, 0x8e, 0xe6, 0x2e, 0x3e, 0xb3, 0x73, 0x6f, 0xbe, 0xfd, 0xf8, 0x10,
	0x4a, 0x20, 0xc4, 0x3f, 0xdb, 0xe5, 0x87, 0xa7, 0xc6, 0x9f, 0x29, 0xd2, 0x39, 0x7a, 0x0d, 0xd1,
	0x11, 0x2b, 0xa1, 0x7f, 0xfc, 0x19, 0x53, 0x2c, 0x76, 0x0d, 0x85, 0x5b, 0xb3, 0x29, 0x20, 0x1c,
	0x1d, 0xa1, 0x50, 0x60, 0xb2, 0xe8, 0x15, 0x44, 0x82, 0xfe, 0x44, 0x5b, 0x93, 0xfb, 0xfb, 0xb6,
	0x65, 0xd9, 0xb1, 0xf1, 0x01, 0xf7, 0xe2, 0xfc, 0x6c, 0x02, 0xab, 0x68, 0x94, 0x00, 0x7a, 0xc7,
	0x40, 0x74, 0xc4, 0x92, 0x81, 0xfd, 0xa7, 0x59, 0x9a, 0xfd, 0xf7, 0xaa, 0xf4, 0x6f, 0x1c, 0x44,
	0x76, 0xda, 0x41, 0xbc, 0x65, 0x20, 0x3a, 0x72, 0x07, 0x02, 0x4c, 0xa6, 0xdd, 0x8d, 0x6b, 0x4e,
	0xa2, 0x30, 0x9b, 0xc3, 0x26, 0x3b, 0x85, 0x43, 0x81, 0xc9, 0x16, 0xf9, 0x8b, 0x2f, 0xa9, 0xb0,
	0x28, 0x8a, 0xb0, 0xd2, 0xd6, 0xd5, 0xc1, 0x84, 0x62, 0xc4, 0x1b, 0x51, 0xb7, 0xbf, 0x1d, 0x75,
	0xe6, 0xb1, 0x77, 0xf7, 0xbb, 0x46, 0xab, 0xb5, 0xe8, 0x7c, 0x4f, 0x6e, 0xfe, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0xaa, 0xa9, 0x1d, 0x3f, 0x5f, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CompanySystemClient is the client API for CompanySystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompanySystemClient interface {
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error)
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error)
	GetCompanies(ctx context.Context, in *GetCompaniesRequest, opts ...grpc.CallOption) (*CompaniesResponse, error)
	DeleteCompany(ctx context.Context, in *DeleteCompanyRequest, opts ...grpc.CallOption) (*DeleteCompanyResponse, error)
	UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error)
}

type companySystemClient struct {
	cc *grpc.ClientConn
}

func NewCompanySystemClient(cc *grpc.ClientConn) CompanySystemClient {
	return &companySystemClient{cc}
}

func (c *companySystemClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error) {
	out := new(CompanyResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/GetCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companySystemClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error) {
	out := new(CompanyResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/CreateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companySystemClient) GetCompanies(ctx context.Context, in *GetCompaniesRequest, opts ...grpc.CallOption) (*CompaniesResponse, error) {
	out := new(CompaniesResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/GetCompanies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companySystemClient) DeleteCompany(ctx context.Context, in *DeleteCompanyRequest, opts ...grpc.CallOption) (*DeleteCompanyResponse, error) {
	out := new(DeleteCompanyResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/DeleteCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companySystemClient) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error) {
	out := new(CompanyResponse)
	err := c.cc.Invoke(ctx, "/company.CompanySystem/UpdateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanySystemServer is the server API for CompanySystem service.
type CompanySystemServer interface {
	GetCompany(context.Context, *GetCompanyRequest) (*CompanyResponse, error)
	CreateCompany(context.Context, *CreateCompanyRequest) (*CompanyResponse, error)
	GetCompanies(context.Context, *GetCompaniesRequest) (*CompaniesResponse, error)
	DeleteCompany(context.Context, *DeleteCompanyRequest) (*DeleteCompanyResponse, error)
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*CompanyResponse, error)
}

// UnimplementedCompanySystemServer can be embedded to have forward compatible implementations.
type UnimplementedCompanySystemServer struct {
}

func (*UnimplementedCompanySystemServer) GetCompany(ctx context.Context, req *GetCompanyRequest) (*CompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}
func (*UnimplementedCompanySystemServer) CreateCompany(ctx context.Context, req *CreateCompanyRequest) (*CompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompany not implemented")
}
func (*UnimplementedCompanySystemServer) GetCompanies(ctx context.Context, req *GetCompaniesRequest) (*CompaniesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanies not implemented")
}
func (*UnimplementedCompanySystemServer) DeleteCompany(ctx context.Context, req *DeleteCompanyRequest) (*DeleteCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompany not implemented")
}
func (*UnimplementedCompanySystemServer) UpdateCompany(ctx context.Context, req *UpdateCompanyRequest) (*CompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}

func RegisterCompanySystemServer(s *grpc.Server, srv CompanySystemServer) {
	s.RegisterService(&_CompanySystem_serviceDesc, srv)
}

func _CompanySystem_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/GetCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanySystem_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanySystem_GetCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).GetCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/GetCompanies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).GetCompanies(ctx, req.(*GetCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanySystem_DeleteCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).DeleteCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/DeleteCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).DeleteCompany(ctx, req.(*DeleteCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanySystem_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanySystemServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.CompanySystem/UpdateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanySystemServer).UpdateCompany(ctx, req.(*UpdateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompanySystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "company.CompanySystem",
	HandlerType: (*CompanySystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompany",
			Handler:    _CompanySystem_GetCompany_Handler,
		},
		{
			MethodName: "CreateCompany",
			Handler:    _CompanySystem_CreateCompany_Handler,
		},
		{
			MethodName: "GetCompanies",
			Handler:    _CompanySystem_GetCompanies_Handler,
		},
		{
			MethodName: "DeleteCompany",
			Handler:    _CompanySystem_DeleteCompany_Handler,
		},
		{
			MethodName: "UpdateCompany",
			Handler:    _CompanySystem_UpdateCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/company/proto/company.proto",
}
