# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  # build
  build:
    docker:
      # specify the version
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/hesabFun/core
    steps:
      - checkout
      - run: curl https://glide.sh/get | sh
      - run: glide install
      - run: cp -r .env.example .env
      - run: go build

  # test
  test:
    docker:
      # specify the version
      - image: circleci/golang:latest
        environment:
          - MYSQL_ADDRESS=localhost
          - MYSQL_DATABASE=hesab_fun
          - MYSQL_USERNAME=root
          - MYSQL_PASSWORD=123456
          - MYSQL_PORT=3306
      - image: mariadb:latest
        environment:
          - MYSQL_DATABASE=hesab_fun
          - MYSQL_ROOT_PASSWORD=123456

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/hesabFun/core
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: curl https://glide.sh/get | sh
      - run: glide install
      - run: go get github.com/rubenv/sql-migrate/...
      - run: sql-migrate up
      - run: sql-migrate up -env=seed
      - run: sql-migrate up -env=test
      - run: cp -r .env.example .env
      - run: go test -v ./...  -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

  # deploy
  deploy:
    docker:
      # specify the version
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/hesabFun/core
    steps:
      - checkout
      - run: curl https://glide.sh/get | sh
      - run: glide install
      - run: cp -r .env.example .env
      - run: go build
      - run: go get github.com/rubenv/sql-migrate/...

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client, build and push Docker image
          command: |
            sudo apt-get update
            sudo apt-get install \
                 apt-transport-https \
                 ca-certificates \
                 curl \
                 gnupg2 \
                 software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository \
               "deb [arch=amd64] https://download.docker.com/linux/debian \
               $(lsb_release -cs) \
               stable"
            sudo apt-get update
            sudo apt-get install docker-ce

            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t hesabfun/core:$TAG .                  # (4)
            docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS    # (5)
            docker push hesabfun/core:$TAG

      # build and push Docker image
#      - run:
#          name: build and push Docker image
#          command: |
#            TAG=0.1.$CIRCLE_BUILD_NUM
#            docker build -t hesabfun/core:$TAG .                  # (4)
#            docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS    # (5)
#            docker push hesabfun/core:$TAG

# Check https://circleci.com/docs/2.0/workflows/ for more details
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build